[grpc]
addr = "0.0.0.0:50053"
enable_tls = false

[http]
addr = "0.0.0.0:8082"
enable_tls = false

enable_swagger = true
enable_web_admin = false
enable_console = true
heartbeat_timeout = 180
cleanup_interval = 600
assignment_reconcile_interval = 60
max_upload_bytes = 67108864
files_dir = "./data/files"
execution_logs_dir = "./data/files/execution_logs"

[web_admin]
addr = "0.0.0.0:8081"
enable_tls = false

[database]
db_type = "sled"
path = "./data/sms"
pool_size = 10

[event_kv]
backend = "sled"
params = { path = "./data/events" }

[logging]
level = "info"
format = "json"
file = "./logs/sms.log"
