{{- if and .Values.spearlet.enabled .Values.spearlet.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spear.spearlet.fullname" . }}
  labels:
    {{- include "spear.labels" . | nindent 4 }}
spec:
  type: {{ .Values.spearlet.service.type }}
  selector:
    {{- include "spear.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: spearlet
  ports:
    - name: grpc
      port: {{ .Values.spearlet.service.grpcPort }}
      targetPort: grpc
    - name: http
      port: {{ .Values.spearlet.service.httpPort }}
      targetPort: http
{{- end -}}
