name: Create Release
on:
  push:
    tags:
    - 'v*.*.*' # 仅在版本标签推送时触发

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许写入内容
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # 拉取完整提交历史
        fetch-tags: true # 关键：拉取所有标签

    - name: Install system dependencies & build release
      run: |
        sudo apt update
        sudo apt install portaudio19-dev libx11-dev libxtst-dev
        make build-release

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          SPEAR release version ${{ github.ref_name }}.
        files: |
          ./target/release/spearlet
          ./target/release/sms
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的令牌
